Add support for GitHub Actions
scoverage/sbt-coveralls pull request #128
Opened 2020-07-16 21:48 UTC by ruippeixotog

This PR generalizes support for CI services other than Travis and provides an implementation for GitHub Actions. The specific implementation was taken by reading the implementations of [coverallsapp/github-action](https://github.com/coverallsapp/github-action) and [nickmerwin/node-coveralls](https://github.com/nickmerwin/node-coveralls) to provide an experience similar to the official GitHub Action.

Besides unit tests, I tested this by publishing a snapshot and testing it on [this branch of PureConfig](https://github.com/pureconfig/pureconfig/tree/coverage-in-github-actions-2), which publishes coverage using both Travis and GitHub Actions. You can compare the results of the [Travis job](https://coveralls.io/builds/32127607) vs the [GitHub Actions job](https://coveralls.io/builds/32127531) (we have non-deterministic tests, so actual coverage is not expected to match exactly).

Closes #126.

2021-05-01 15:00 UTC, ckipp01 commented
Thanks for the pr @ruippeixotog. Are you by chance able to give this another look-through an ensure everything is still up to date and valid. If so I can do a review of this and try to move it across the finish line.

2021-05-01 19:36 UTC, ruippeixotog commented
Hi! We're still using a release with this PR on PureConfig (https://github.com/pureconfig/pureconfig/pull/799). You can find the coverage for the latest CI build in https://coveralls.io/builds/39270988, everything seems to be working well.

2021-05-06 12:26 UTC, ckipp01 requested changes
Thanks a lot for this @ruippeixotog. This is all pretty much fine. The only other thing would be to update the README to change some of the wording to no longer imply that it's only for Travis, and also include a small snippet as an example for someone to know how to use this via GitHub actions. After that this is good to go!

2021-05-10 20:38 UTC, ruippeixotog commented
@ckipp01 here you go, let me know if you need any other changes.

2021-05-25 11:43 UTC, ckipp01 approved these changes
Thanks a lot @ruippeixotog, this looks great!

2021-05-25 11:43 UTC, merged

2021-06-13 13:57 UTC, ruippeixotog commented
@ckipp01 when will you be able to release a new coveralls version with these changes?

2021-06-13 14:05 UTC, ckipp01 commented
> @ckipp01 when will you be able to release a new coveralls version with these changes?

Hey! Sorry for the delay. Should find some time in the next couple days. It's on my list.

2021-06-13 14:08 UTC, ckipp01 commented
Actually take that back, I just triggered a release. We'll see if all the release stuff is set up correctly. If so, you'll see it available after it syncs.

2021-06-14 20:36 UTC, ruippeixotog commented
Works perfectly, thanks!

2021-12-21 08:52 UTC, leobenkel commented
is that deployed in the latest version ? I am using version 1.3.1

2021-12-21 08:59 UTC, ckipp01 commented
> is that deployed in the latest version ? I am using version 1.3.1

Yes, it should be there.